version: '3'
services:
  app:
    container_name: ${PROJECT_NAME}-app
    image: webdevops/php-nginx-dev:7.4
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_DEBUGGER=xdebug
      - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT}
      - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_MAX_NESTING_LEVEL=1500
    ports:
      - '${DOCKER_APP_PORT}:80'
    networks:
      - glofox-network
    depends_on:
      - db

  db:
    container_name: ${PROJECT_NAME}-mongodb
    image: mongo
    restart: always
    volumes:
      - ./.docker/data/mongodb:/data/db
    ports:
      - '${DOCKER_MONGODB_PORT}:27017'
    networks:
      - glofox-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

networks:
  glofox-network:
    driver: bridge
